platform :ios, '10.0'
use_frameworks!

target 'GoogleNearbyPlaces_Example' do
  pod 'GoogleNearbyPlaces', :path => '../'

  target 'GoogleNearbyPlaces_Tests' do
    pod 'GoogleNearbyPlaces', :path => '../'

    
  end
end
