use_frameworks!

target 'CCXGoogleNearbyPlaces_Example' do
  pod 'CCXGoogleNearbyPlaces', :path => '../'

  target 'CCXGoogleNearbyPlaces_Tests' do
    pod 'CCXGoogleNearbyPlaces', :path => '../'

    
  end
end
